version: '3'
services:
  rabbitmq:
    image:  rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: root 
      RABBITMQ_DEFAULT_PASS: admin1234  
    ports:
      - "5672:5672"
      - "15672:15672"
  app:
    build: .
    command: bash -c "celery -A workers worker -l info"
    restart: always
    volumes:
      - ./:/workspace/
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root 
      RABBITMQ_DEFAULT_PASS: admin1234  